name: Vero
options:
  minimumXcodeGenVersion: 2.44.0
  deploymentTarget:
    macOS: "13.0"
settings:
  base:
    PRODUCT_NAME: "$(TARGET_NAME)"
    SWIFT_VERSION: 5.9
    MACOSX_DEPLOYMENT_TARGET: "13.0"
    CODE_SIGN_IDENTITY: "-"
    CODE_SIGN_STYLE: Manual
    CODE_SIGNING_REQUIRED: NO
    CODE_SIGNING_ALLOWED: NO
targets:
  Vero:
    type: application
    platform: macOS
    sources:
      - path: Vero
        excludes:
          - AgentRuntime.swift
          - Info.plist
          - MenuBarManager.swift
          - MenuBarView.swift
          - "*.entitlements"
      - path: Shared
    dependencies:
      - target: VeroAgent
        embed: true
        link: false
        copy:
          destination: wrapper
          subpath: Contents/Library/LoginItems
    settings:
      base:
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        PRODUCT_NAME: Vero
        PRODUCT_BUNDLE_IDENTIFIER: com.naboulsi.vero
        INFOPLIST_FILE: Vero/Info.plist
        OTHER_CODE_SIGN_FLAGS: "- --identifier $(PRODUCT_BUNDLE_IDENTIFIER)"
    scheme:
      gatherCoverageData: false
  VeroAgent:
    type: application
    platform: macOS
    sources:
      - path: VeroAgent
        excludes:
          - Info.plist
          - "*.entitlements"
      - path: Shared
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.naboulsi.vero.agent
        INFOPLIST_FILE: VeroAgent/Info.plist
        SKIP_INSTALL: YES
        OTHER_CODE_SIGN_FLAGS: "- --identifier $(PRODUCT_BUNDLE_IDENTIFIER)"
    scheme:
      gatherCoverageData: false
